version: 3

tasks:
  run:
    cmds:
      - go run ./cmd/winproxy

  build:
    cmds:
      - go build -v ./cmd/winproxy

  install:
    cmds:
      - go install ./cmd/winproxy

  test:
    cmds:
      - go test -v ./...