// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package i18n

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US":   &dictionary{index: en_USIndex, data: en_USData},
		"zh_Hans": &dictionary{index: zh_HansIndex, data: zh_HansData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Additional Commands":    4,
	"Additional help topics": 7,
	"Aliases":                1,
	"Auto-detect":            19,
	"Available Commands":     3,
	"Bypass list":            20,
	"Examples":               2,
	"Flags":                  5,
	"Global Flags":           6,
	"Proxy address":          16,
	"Script address":         18,
	"Usage":                  0,
	"Use \"%s\" for more information about a command.": 8,
	"Use proxy":                     15,
	"Use script":                    17,
	"automatically detect settings": 13,
	"bypass list":                   14,
	"proxy address":                 10,
	"script address":                12,
	"use a proxy server":            9,
	"use setup script":              11,
}

var en_USIndex = []uint32{ // 22 elements
	0x00000000, 0x00000006, 0x0000000e, 0x00000017,
	0x0000002a, 0x0000003e, 0x00000044, 0x00000051,
	0x00000068, 0x0000009a, 0x000000ad, 0x000000bb,
	0x000000cc, 0x000000db, 0x000000f9, 0x00000105,
	0x0000010f, 0x0000011d, 0x00000128, 0x00000137,
	0x00000143, 0x0000014f,
} // Size: 112 bytes

const en_USData string = "" + // Size: 335 bytes
	"\x02Usage\x02Aliases\x02Examples\x02Available Commands\x02Additional Com" +
	"mands\x02Flags\x02Global Flags\x02Additional help topics\x02Use \x22%[1]" +
	"s\x22 for more information about a command.\x02use a proxy server\x02pro" +
	"xy address\x02use setup script\x02script address\x02automatically detect" +
	" settings\x02bypass list\x02Use proxy\x02Proxy address\x02Use script\x02" +
	"Script address\x02Auto-detect\x02Bypass list"

var zh_HansIndex = []uint32{ // 22 elements
	0x00000000, 0x00000007, 0x0000000e, 0x00000015,
	0x00000022, 0x0000002f, 0x00000036, 0x00000043,
	0x00000056, 0x0000008d, 0x000000a3, 0x000000b0,
	0x000000c3, 0x000000d0, 0x000000e3, 0x0000010b,
	0x00000121, 0x0000012e, 0x00000141, 0x0000014e,
	0x00000161, 0x00000189,
} // Size: 112 bytes

const zh_HansData string = "" + // Size: 393 bytes
	"\x02用法\x02别名\x02例子\x02可用命令\x02附加命令\x02标志\x02全局标志\x02其他帮助主题\x02使用 \x22%[1" +
	"]s\x22 获取关于某个命令的更多信息\x02使用代理服务器\x02代理地址\x02使用设置脚本\x02脚本地址\x02自动检测设置\x02不" +
	"使用代理服务器的地址列表\x02使用代理服务器\x02代理地址\x02使用设置脚本\x02脚本地址\x02自动检测设置\x02不使用代理服务" +
	"器的地址列表"

	// Total table size 952 bytes (0KiB); checksum: CD87AC38
