version: 3

includes:
  i18n:
    dir: cmd
    taskfile: cmd/i18n.yaml

tasks:
  run:
    cmds:
      - go run ./cmd/winproxy {{.CLI_ARGS}}

  build:
    cmds:
      - go build -v ./cmd/winproxy

  install:
    cmds:
      - go install ./cmd/winproxy

  test:
    cmds:
      - go test -v ./...
