[package]
name = "winproxy-cli"
version = "0.7.5"
edition = "2024"
rust-version = "1.88"
description = "Change Windows system proxy settings"
categories = ["command-line-utilities"]
keywords = ["windows", "proxy"]
repository = "https://github.com/fhluo/winproxy"
readme = "../README.md"
license = "MIT"

[[bin]]
name = "winproxy"
path = "src/main.rs"

[dependencies]
winproxy = { version = "0.7", path = "../winproxy" }
clap = { version = "4.6", features = ["derive", "string"] }
anstream = "1.0"
tabled = { version = "0.21", features = ["ansi"] }
fluent-templates = "0.15"
sys-locale = "0.3"
icu_locale = "2.3"
