name: Build

on:
  push:
    branches: [ "main" ]
    tags: ["v*.*.*"]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      GOOS: windows
      GOARCH: amd64
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Set up Task
        uses: arduino/setup-task@v2

      - name: Build
        run: task go:build

      - name: Test
        run: task go:test

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: go/winproxy.exe
