name: Build Go

on:
  push:
    branches: [ "main" ]
    paths:
      - 'go/**'
      - '.github/workflows/build-go.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'go/**'
      - '.github/workflows/build-go.yaml'

jobs:
  build-go:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: 'stable'
          cache-dependency-path: 'go/go.sum'

      - name: Build
        working-directory: go
        run: go build ./cmd/winproxy

      - name: Test
        working-directory: go
        run: go test ./...
