name: Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'go/**'
      - '.github/workflows/build-go.yaml'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'go/**'
      - '.github/workflows/build-go.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v2
        with:
          rustflags: ""

      - name: Set up Nushell
        run: |
          winget install -e --id=Nushell.Nushell --accept-source-agreements --accept-package-agreements
          "$env:LOCALAPPDATA\Programs\nu\bin" | Out-File -FilePath "$env:GITHUB_PATH" -Append

      - name: Set up Just
        uses: extractions/setup-just@v4

      - name: Build
        run: just build

      - name: Test
        run: just test
