name: Release

on:
  push:
    tags: [ "v*.*.*" ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""

      - name: Set up Task
        uses: go-task/setup-task@v2

      - name: Build
        run: |
          task build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: |
            target/**/release/winproxy.exe
